services:
  - type: web
    name: flight-booking-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    region: oregon
    envVars:
      - key: DATABASE_URL
        scope: build
      - key: AMADEUS_CLIENT_ID
        scope: build
      - key: AMADEUS_CLIENT_SECRET
        scope: build
      - key: SECRET_KEY
        scope: build
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        scope: build
      - key: MAIL_PASSWORD
        scope: build
      - key: MAIL_FROM
        scope: build
